server:
  port: 8090

spring:
  application:
     name: PhoneApp
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
      
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto:  
    database-platform: org.hibernate.dialect.H2Dialect
