CREATE TABLE PUBLIC.TPHONES 
(
	ID NUMBER NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	IMAGE VARCHAR(255) NOT NULL,
	PRICE INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.TORDERS 
(
	ID NUMBER NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	SURNAME VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.TORDERS_PHONES 
(
	TORDERS_ID NUMBER NOT NULL,
	PHONES_ID NUMBER NOT NULL,
);
CREATE UNIQUE INDEX UI_TORDERS_PHONES ON TORDERS_PHONES(TORDERS_ID, PHONES_ID);
