CREATE TABLE PUBLIC.TPHONES 
(
	ID INTEGER NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	IMAGE VARCHAR(255) NOT NULL,
	PRICE INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
COMMIT;
